buildscript{
    repositories{
        jcenter()
    }

    dependencies{
        classpath'com.github.jengelman.gradle.plugins:shadow:5.2.0'
    }
}

plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '5.2.0'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

compileJava.options.encoding = 'UTF-8'

repositories {
    mavenCentral()

    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
    maven { url 'https://repo.dmulloy2.net/repository/public/' }
    maven { url 'https://repo.s8u.kr/repository/maven-minecraft/' }
    maven { url 'https://repo.s8u.kr/repository/maven-pooleaf/' }
}

dependencies {
    compileOnly 'io.papermc:paper:1.8.8'
    compileOnly 'net.md-5:bungeecord-api:1.18-R0.1-SNAPSHOT'

    compileOnly 'com.comphenix.protocol:ProtocolLib:4.7.0'

    implementation 'com.zaxxer:HikariCP:4.0.3'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.0.3'
    implementation 'io.lettuce:lettuce-core:6.0.0.RELEASE'

    compileOnly 'org.projectlombok:lombok:1.18.20'
    annotationProcessor 'org.projectlombok:lombok:1.18.20'


    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'

    testImplementation 'com.google.code.gson:gson:2.9.0'

    testCompileOnly 'io.lettuce:lettuce-core:6.0.0.RELEASE'

    testCompileOnly 'org.projectlombok:lombok:1.18.20'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.20'
}

processResources {
    filesMatching('**/*.yml') {
        expand(project.properties)
    }
}

shadowJar {
    archiveBaseName.set(pluginName)
    archiveClassifier.set('')

    relocate 'io.netty', 'io.lettuce.netty'
}

task copyToServerWindows(type: Copy) {
    from(shadowJar)
    into('D:\\서버\\1.8.9 테스트 서버\\update')
}