buildscript{
    repositories{
        jcenter()
    }

    dependencies{
        classpath'com.github.jengelman.gradle.plugins:shadow:5.2.0'
    }
}

plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '5.2.0'
    id 'maven-publish'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

compileJava.options.encoding = 'UTF-8'

dependencies {
    implementation project(':java')
    implementation project(':kotlin')
}

allprojects {
    apply plugin: 'java'

    repositories {
        mavenCentral()

        maven { url 'https://libraries.minecraft.net/' } // Mojang (brigadier)
        maven { url 'https://repo.s8u.kr/repository/maven-minecraft/' } // Bukkit
        maven { url 'https://repo.s8u.kr/repository/maven-pooleaf/' } // Core
        maven { url 'https://repo.dmulloy2.net/repository/public/' } // ProtocolLib, XSeries
    }

    dependencies {
        // Platform
        compileOnly 'io.papermc:paper-api:1.8.8'
        compileOnly 'net.md-5:bungeecord-api:1.20-R0.2'

        // Bukkit Library
        compileOnly 'com.comphenix.protocol:ProtocolLib:4.8.0'
        implementation 'com.github.cryptomorin:XSeries:9.1.0'

        // SQL
        implementation 'com.zaxxer:HikariCP:4.0.3'
        implementation 'org.mariadb.jdbc:mariadb-java-client:3.0.3'

        // Redis
        implementation 'io.lettuce:lettuce-core:6.0.0.RELEASE'

        // JSON
        implementation 'com.google.code.gson:gson:2.10.1'

        // Guava
        implementation 'com.google.guava:guava:31.1-jre'

        // Cache
        implementation 'net.sf.ehcache:ehcache:2.10.9.2'

        // Lombok
        compileOnly 'org.projectlombok:lombok:1.18.30'
        annotationProcessor 'org.projectlombok:lombok:1.18.30'
    }
}

publishing {
    repositories {
        maven {
            url "https://repo.s8u.kr/repository/maven-pooleaf/"
            credentials {
                username = System.getenv("NEXUS_USERNAME")
                password = System.getenv("NEXUS_PASSWORD")
            }
        }
    }

    publications {
        maven(MavenPublication) {
            artifact(shadowJar)
        }
    }
}

processResources {
    filesMatching('**/*.yml') {
        expand(project.properties)
    }
}

shadowJar {
    delete 'build/resources'

    archiveClassifier.set('')

    relocate 'io.netty', 'net.pooleaf.core.lib.io.lettuce.netty'
    relocate 'com.google.gson', 'net.pooleaf.core.lib.com.google.gson'
    relocate 'com.google.common', 'net.pooleaf.core.lib.com.google.common'
}

task copyToServerWindows(type: Copy) {
    from(shadowJar)
    into('D:\\서버\\1.8.9 LeafServer S6\\.plugin_build')
}